tap "oven-sh/bun"
tap "waydabber/betterdisplay"
brew "bat"
brew "bun"
brew "neovim"
brew "node"
brew "fastfetch"
brew "fish"
brew "fisher"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
# brew "hadolint"
brew "htop"
brew "iperf3"
brew "lazygit"
brew "lefthook"
brew "openjdk"
brew "openssh"
brew "pandoc"
brew "posting"
brew "rust"
brew "stow"
# brew "tmux"
brew "uv"
brew "whalebrew"
brew "yazi"
cask "aldente"
cask "betterdisplay"
cask "bettertouchtool"
cask "chatgpt"
cask "cleanmymac"
cask "downie"
# cask "font-jetbrains-mono-nerd-font"
cask "font-sf-compact"
cask "font-sf-mono"
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-sf-pro"
cask "jordanbaird-ice"
# cask "mactex-no-gui"
# cask "motrix"
cask "notchnook"
cask "notion"
cask "orbstack"
cask "stats"
cask "surge"
cask "tailscale-app"
# cask "tor-browser"
cask "wechat"
cask "qq"

# Mas
mas "AdGuard for Safari", id: 1440147259
mas "Developer", id: 640199958
mas "Immersive Translate", id: 6447957425
mas "Infuse", id: 1136220934
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "MindNode", id: 6446116532
mas "Noir", id: 1592917505
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tampermonkey", id: 6738342400
mas "TestFlight", id: 899247664
mas "Transporter", id: 1450874784
mas "Xcode", id: 497799835

# Microsoft
mas "Windows App", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816

brew "waydabber/betterdisplay/betterdisplaycli"
